name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore: 
      - .github/**
  pull_request:
    branches: 
      - main
      
  schedule:
    - cron: 15 6 * * 0
    
  workflow_dispatch:
    
jobs:
  build:  
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Triggered by ${{ github.event_name }}"
          echo "on branch ${{ github.ref }}"
          ls -R
          
      
        
      
    
